### ISSUE TITLE
Having issues setting zoom

### ISSUE THREAD

**Issue by KingCosmic** [britzl/defold-orthographic#11]
Hello there! I've tried setting zoom straight from the properties on the camera.go and changing it through script. But each time it seem's to have no effect at all.

**Comment by britzl** [comment]
Can you verify that you are using a projection other than "default"? The "default" projection is like the default render script of a Defold project where the content is stretched to fill the screen, regardless of zoom. You probably want FIXED_ZOOM instead of DEFAULT.

**Comment by KingCosmic** [comment]
That seems to be the issue, sorry for your troubles and great plugin!
