### ISSUE TITLE
weird position of camera when camera bounds less than windows size

### ISSUE THREAD

**Issue by TinyDobbins** [britzl/defold-orthographic#14]
something going weird when window_width or window_height bigger than camera_bounds.
in version 2.3.1 all okay with that.

**Comment by britzl** [comment]
Would you mind testing latest master? I've made some changes to how bounds are handled when zoomed out much or when bounds is less than window size.

**Comment by TinyDobbins** [comment]
@britzl tested, works better now, but still something weird with camera_bounds, 
I will make a test-project now.
need to create for example 800x600 game. with `FIXED_AUTO` camera.  with bounds:
`msg.post(CAMERA_ID, "bounds", { left = 0, right = 2000, bottom = -100, top = 1000 })`

**Comment by britzl** [comment]
Hmm, ok, I'll try with the settings you provided.

**Comment by TinyDobbins** [comment]
I added the test project `test_defold_orthographic` and sent invite to you.

**Comment by britzl** [comment]
I compared with the wrong values when I did the bounds limitation. Please try latest master again.

**Comment by TinyDobbins** [comment]
Yes, it works perfectly! Thanks a lot for fixing this issue.

**Comment by britzl** [comment]
Excellent! Released 2.7.0
