### ISSUE TITLE
How to calculate MinX, MinY, MaxX, MaxY on real device when using FIXED_AUTO mode

### ISSUE THREAD

**Issue by takaaptech** [britzl/defold-orthographic#15]
Hi @britzl !
Thank so much for creating an awesome camera plugin
I am new in Defold and I want to control the game object base on the edge of the real device on runtime, via script.
So basically here is some input:
Display params on game.project: Width 640, Height 960
Projection mode: FIXED_AUTO
When running on real device it logs:
camera.get_display_size()	640	960
camera.get_window_size()	1080	1920

Now I want to calculate the MINX, MINY so when I set the position of a sprite (In the script, not in the editor), it is always on the bottom left of any real device.
(It is the bound of the real device - MinX, MinY, W, H or MinX, MinY, MaxX, MaxY)
(It is expected MinX, MinY to be a negative value on some device, it calculates base on display_size,window_size, zoom,  and that value will relative with  display_size)
Also, I notice that if using camera plugin, now 0,0 in editor convert to the center of the real device?

Thank so much!

**Comment by britzl** [comment]
Ok, so you want a game object positioned bottom left? You should be able to use:

```
local camera_id = hash("mycamera")
local screen = vmath.vector3(0,0,0)
local lower_left = camera.screen_to_world(camera_id, screen)
go.set_position(lower_left, "mygameobject")

```
What happens is that we convert a screen coordinate (0,0) to a world coordinate (ie based on position of camera in the world offset to lower left corner).

> Also, I notice that if using camera plugin, now 0,0 in editor convert to the center of the real device?

Yes, the camera will center on the position of the camera.go.

**Comment by takaaptech** [comment]
Hi @britzl 
It is incredible! I just test and it works like a charm on my real device!
So how to get the top right of the real device? I still have a little bit confuse about :
local screen = vmath.vector3(0,0,0) 
Why 0,0 for lower_left? and what should we put in that vector to get top right?

Thank so much!

**Comment by takaaptech** [comment]
I also found the function that maybe fit my question:
camera.screen_to_world_bounds(camera_id)

**Comment by britzl** [comment]
Yes, camera.screen_to_world_bounds(camera_id) would be of use to you.

Otherwise you can use something like this:

```
local width, height = camera.get_window_size()
local camera_id = hash("mycamera")
local screen = vmath.vector3(width, height, 0)
local top_right = camera.screen_to_world(camera_id, screen)
go.set_position(top_right, "mygameobject")
```

**Comment by takaaptech** [comment]
Hi @britzl 
I think it should be:
```
 local width, height = camera.get_display_size()
```
Could you please confirm it?

And other question is that camera.get_display_size() and camera.get_window_size() only work outside init function? If I put 2 methods in init then the return values are equals
If I move it to on_input for the test, it is work as expected.
Thanks!

**Comment by britzl** [comment]
Hmm, yes, that might be correct. camera.get_display_size() will return the size you have in game.project while camera.get_window_size() will return resized window size.

camera.get_window_size() will not update until after the render script has had a chance to run once. That is why you can't call it in the init() function of a script.

**Comment by takaaptech** [comment]
Thank so much!
