### ISSUE TITLE
Feature request: Query boundaries at a certain zoom level

### ISSUE THREAD

**Issue by totebo** [britzl/defold-orthographic#18]
I’d like to know the bounds of the screen before I zoom out and/or move camera, so I can set the correct offset based on screen size.

Maybe screen_to_world_bounds extra parameters:

`camera.screen_to_world_bounds( camera_id, [camera_position], [zoom] )`

**Comment by britzl** [comment]
Hmm, not really sure I understand this one. You wish to know the bounds of the screen when a certain zoom level is applied (but before actually using camera.set_zoom)? Could you perhaps divide the values returned by camera.screen_to_world_bounds() to get the values you want?

**Comment by totebo** [comment]
Yeah you're right, that should work! 🙄

**Comment by britzl** [comment]
Closing. Re-open if it doesn't work and we'll discuss alternatives.
