### ISSUE TITLE
camera.world_to_screen() returns the incorrect position if window has been resized

### ISSUE THREAD

**Issue by totebo** [britzl/defold-orthographic#23]
Works as intended when window hasn't been resized.

Discussion: 
https://forum.defold.com/t/creating-a-gui-node-in-the-same-visual-position-as-a-game-object/46299/7

**Comment by britzl** [comment]
Started looking into this. It all depends on the adjust mode of the node. Adjust Mode set to Stretch will always be positioned correct, but Fit and Zoom will stray.

I probably need to add either a separate `camera.world_to_adjusted_screen(camera, world)` or `camera.world_to_screen(camera, world, adjust_mode)`

**Comment by totebo** [comment]
Great! Fyi, I tried to change the 0,0 holder node to stretch (but the copied node is fit) and that didn't seem to work.

**Comment by totebo** [comment]
This one is still on my todo list. Do you think it's fixable, or should I try to come up with a workaround?

**Comment by britzl** [comment]
I'm investigating it. It should be doable. I'm currently playing with a solution based on camera.world_to_screen(camera, world, adjust_mode)

**Comment by totebo** [comment]
Fantastic, sorry for the nagging. :)

**Comment by britzl** [comment]
I'm currently not making any progress on this. My head is currently unable to wrap itself around the math of this.... RenderCam is supposedly able to do this so you might want to look into migrating camera solution.

**Comment by totebo** [comment]
Noooooooooooooo!

**Comment by totebo** [comment]
Is it not possible to use the maths from `camera.screen_to_world_bounds()`, which sort of does this (in reverse)?

**Comment by totebo** [comment]
Is it not possible to copy the solution from RenderCam? I'd hate to change cameras now when I have Ortho so tightly integrated.

**Comment by britzl** [comment]
I finally figured this out. A new version with camera.world_to_screen(camera_id, world, [adjust_mode]) has been released: https://github.com/britzl/defold-orthographic/releases/tag/2.8.0

**Comment by totebo** [comment]
LEGENDARY! Thank you och tack!
