### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by jamesaorson** [britzl/defold-orthographic#24]
I am having problems getting the zoom to work. Even following the example in the repo I cannot seem to get my code working. A minimal example which utilizes some of the same libraries I am using has been created in a [branch on my Gitlab](https://gitlab.com/JamesOsborne/Chemaria/tree/Minimal-orthographic-example). The issue is present in this example.

**Comment by britzl** [comment]
You are using the default render script in game.project. You need to either use the render script provided by Orthographic or create your own and integrate Orthographic with the renderscript. More info here: https://github.com/britzl/defold-orthographic#1-using-the-provided-render-script
