### ISSUE TITLE
Documentation for animate with "zoom"

### ISSUE THREAD

**Issue by totebo** [britzl/defold-orthographic#26]
It took me a little while to figure out how to zoom with the camera using go.animate. When referencing the camera, it seems you have to use "camera#script" instead of camera, camera id or "camera".

If this is true, maybe change:

`go.animate(camera, "zoom", ...)`

To:

`go.animate("camera#script", "zoom", ...)`

**Comment by britzl** [comment]
Good point! I've updated the documentation: https://github.com/britzl/defold-orthographic/blob/master/README.md#zoom-number
