### ISSUE TITLE
camera.screen_to_world doesn't actually work?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-orthographic#3]
I was expecting this to work like rendercam.screen_to_world_2d(screen_x, screen_y) but it doesn't seem to produce similar results when using screen_x and screen_y mouse position data?

![zz](https://user-images.githubusercontent.com/409170/38257874-02932c8e-3716-11e8-8c5a-572c8c8ceef6.png)

Should I be using camera.unproject ? it doesn't seem very user friendly  (I'll read the source soon..)

**Comment by subsoap** [comment]
I see it works with action.x and action.y but I need something which works with screen_x and screen_y

**Comment by britzl** [comment]
Ah, yes, I've only thought of it used for action.x and y. Hmm, need to think of the implication of the use of screen_x/y. When/why would you want to use one instead of the other?

**Comment by subsoap** [comment]
The reason I had was with the multitouch html5 project I'm working on. I ended up converting screen_x/y positions to x/y positions inside of the multitouch code based on some of your older code.
```
	function update_zoom_factor() {
		zoom_factor = Math.min(game_canvas.width / original_width, game_canvas.height / original_height); 
	}
	
	function filter_position(x,y) {
		x = x / zoom_factor;
		y = y / zoom_factor;
		return {x:x, y:y};
	}
```

**Comment by britzl** [comment]
Huh, ok, but why did you need screen_x/y? The screen to world function works when passing action.x/y regardless of how you've resized your window. There should be no need to use screen_x/y

**Comment by subsoap** [comment]
No, I converted screen_x/y to x/y because screen_x/y is what I had access to on the JS side with the multitouch values.

**Comment by britzl** [comment]
Ok, I see. So there should perhaps be one window_to_world() and one screen_to_world() function or something like that. Or maybe just change it to always expect screen_x/y. But then the opposite might happen and someone needs to work with x/y and not screen_x/y...

**Comment by britzl** [comment]
Added camera.window_to_world() and added documentation explaining the terminology used by the API
