### ISSUE TITLE
Camera gets offset when resizing window and using bounds

### ISSUE THREAD

**Issue by JustAPotota** [britzl/defold-orthographic#32]
In my game, I have the camera (FIXED_ZOOM) set to follow the player, and automatically set the bounds to the level tilemap dimensions. Everything works great until the window gets resized, then the camera gets shifted up and to the right, with the player no longer in the center.

Before resizing window (how it _should_ look):
![Default](https://user-images.githubusercontent.com/43710172/81957427-284c9600-95d2-11ea-940b-790ced00b5d4.gif)

After resizing window (now the camera is offset):
![resized](https://user-images.githubusercontent.com/43710172/81957853-c50f3380-95d2-11ea-94cb-d59beb645f31.gif)

### [Minimal example project](https://github.com/britzl/defold-orthographic/files/4629506/ortho-bounds-test.zip)

**Comment by britzl** [comment]
I've received reports of problems with the bounds functionality. I'm sorry for this. I will try to take a look soon.

**Comment by JustAPotota** [comment]
Any updates on this?

**Comment by britzl** [comment]
I'm sorry but with all of the work with the foundation and the launch of the Defold source code I haven't had time to look into this yet.

**Comment by JustAPotota** [comment]
Have you had time to look into this yet?

**Comment by britzl** [comment]
No, sorry I haven't

**Comment by britzl** [comment]
Solved: https://github.com/britzl/defold-orthographic/pull/37
