### ISSUE TITLE
window.get_size is nil?

### ISSUE THREAD

**Issue by notexplosive** [britzl/defold-orthographic#33]
Hi, I'm pretty new to Defold but I'm fairly familiar with Lua (I'm a LOVE2D dev considering making the switch). It's entirely possible I messed up somewhere but I'm not sure.

Here's the steps I followed, which should be essentially just following the readme:
- Imported the dependency as instructed in the readme: https://github.com/britzl/defold-orthographic/archive/master.zip
- Fetched dependencies so I have access to it
- In my game.project I set `/orthographic/render/orthographic.render` as my Render
- In my main.collection I added a game object from a file as `/orthographic/camera.go`
- CTRL+B to build and run and... I get an error!

```
ERROR:SCRIPT: /orthographic/camera.lua:153: attempt to call field 'get_size' (a nil value)
stack traceback:
	/orthographic/camera.lua:153: in function 'update_window_size'
	/orthographic/camera.lua:280: in function 'update'
	/orthographic/camera.script:70: in function </orthographic/camera.script:68>
```

Seems straightforward enough, window.get_size appears to be nil. So I popped a breakpoint and inspected the "window" table:

```
{ -- <table: 0x01fe3955bc60>
  DIMMING_OFF = 2,
  DIMMING_ON = 1,
  DIMMING_UNKNOWN = 0,
  WINDOW_EVENT_FOCUS_GAINED = 1,
  WINDOW_EVENT_FOCUS_LOST = 0,
  WINDOW_EVENT_RESIZED = 2,
  get_dim_mode = <function: 0x01fe3955be00>,
  set_dim_mode = <function: 0x01fe3955bd90>,
  set_listener = <function: 0x01fe3955bd20>
}
```

According to the [API Docs](https://defold.com/ref/stable/window/#window.get_size:) this looks like the right "window" table except for it's missing exactly one function: get_size.

To confirm, I tried to check for window.get_size and sure enough it's nil.
```
> window.get_size
= 
> window.get_size == nil
= true
```

I did a CTRL+SHIFT+F to search for anything that might have assigned over the value of `window.get_size` and found nothing. The only usage of `get_size` in my project is the line we're crashing on. This to me looks indicative of window.get_size being deprecated but I don't see any indication that it is.

I'm sure this is an obvious "oh you forgot to do X" that comes with learning any new technology but I'm honestly kind of stumped.

**Comment by britzl** [comment]
This sounds really odd. Which version of Defold are you using? And you don't happen to have any other script which accidentally sets window.get_size to nil or something like that?

**Comment by notexplosive** [comment]
Thanks for the super fast reply! I was using an out of date version (apparently window.get_size is a new feature?). My "new update available" link wasn't doing anything so I went and installed it again from the website.

Is there an easy way to tell from the API docs how "new" a given part of the API is? I think I could have deduced this much faster if it said "added in version x.x.x"

Closing this issue: cause was user error 👍

**Comment by britzl** [comment]
> apparently window.get_size is a new feature

It's been there for quite some time I think.

> Is there an easy way to tell from the API docs how "new" a given part of the API is? I think I could have deduced this much faster if it said "added in version x.x.x"

No, but it is a good suggestion. We'll try to adopt this for new functions in the future (although we add new things to the API rarely)
