### ISSUE TITLE
screen_to_world return a z value of 1

### ISSUE THREAD

**Issue by gianmichelemariani** [britzl/defold-orthographic#34]
Just trying out the module. It seems that the vector returned by screen_to_world has a z value of 1 (instead of the 0 passed).
Is this correct behaviour?

<img width="656" alt="Screenshot 2020-12-10 at 16 06 54" src="https://user-images.githubusercontent.com/46694168/101797585-1ef0c100-3b02-11eb-8e10-80c1dce49197.png">

**Comment by britzl** [comment]
Hmm no, that doesn't sound right. It should respect the value you pass in.
