### ISSUE TITLE
Breaking change to camera.world_to_screen() in v2.11.2.

### ISSUE THREAD

**Issue by totebo** [britzl/defold-orthographic#39]
world_to_screen() returns incorrect results if v2.11.2 or later is used. v2.11.1 or earlier works.

Forum thread: https://forum.defold.com/t/creating-a-gui-node-in-the-same-visual-position-as-a-game-object-solved/46299/10

**Comment by totebo** [comment]
Test project: 
[OrthographicWorldToScreen.zip](https://github.com/britzl/defold-orthographic/files/6142003/OrthographicWorldToScreen.zip)

**Comment by britzl** [comment]
Fixed in: https://github.com/britzl/defold-orthographic/releases/tag/2.11.4
