### ISSUE TITLE
Gui and Orthographic 

### ISSUE THREAD

**Issue by RomanAnchugov** [britzl/defold-orthographic#4]
So, i’ve started working with Orthographic asset for camera. Also, i used “shake” method, but the problem is that this method doesnt affect gui on my screen.
Is it possible to “shake” gui by this method too?

**Comment by britzl** [comment]
The camera.script now has an Offset Gui checkbox. Orthographic will send camera offset every frame while this option is enabled. The included render script will use the offset to change GUI projection as well to match the shake/recoil effect.
