### ISSUE TITLE
[QUESTION] What would be equivavlent to older version of camera.set_window_size() ?

### ISSUE THREAD

**Issue by Dzuvan** [britzl/defold-orthographic#45]
I have an issue when using this library together with the lowrez template where the contents of the screen become super pixelated and unreadable even for lowrez.

I'm using custom render script that is copy pasta of the lowrez render script with added viewport setting in the update function that comes the new version of the lib.

The workaround is to set display width and height in game.project but that causes an issue when uploading to itch where the game is running in a super small window.

As far as I can see in the older versions that would have been done with set_window_size but what to do now?

**Comment by britzl** [comment]
Hi! The old camera.set_window_size() function was called from the render script to update the window size (here from version 2.10.0):

https://github.com/britzl/defold-orthographic/blob/2.10.0/orthographic/camera.lua#L129-L159

In later versions this is done automatically in camera.update():

https://github.com/britzl/defold-orthographic/blob/master/orthographic/camera.lua#L321

And as you can see the actual code is (almost) the same:

https://github.com/britzl/defold-orthographic/blob/master/orthographic/camera.lua#L159-L194

------

One solution would be that you use version 2.10.0. Add this as your dependency in game.project:

https://github.com/britzl/defold-orthographic/archive/refs/tags/2.10.0.zip

**Comment by Dzuvan** [comment]
Reverting to 2.10.0 does the trick, thanks!
