### ISSUE TITLE
Disable stencil test

### ISSUE THREAD

**Issue by Sayuris1** [britzl/defold-orthographic#47]
Clip node clips the profiler too if stencil test is not disabled at the end of the render script. I think we should add
``` render.disable_state(render.STATE_STENCIL_TEST) ``` after drawing gui in orthographic.render_script.

**Comment by britzl** [comment]
Closed via https://github.com/britzl/defold-orthographic/commit/10d7d3c1d17d754ea3618138d83ca79ef03a59b7
