### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by ghost** [britzl/defold-orthographic#49]
Hi, lots of thanks for your work.
I found a little typo in the readme, i wanted to copy / paste and that ended in an error. :)

<img width="612" alt="Capture d’écran 2021-12-20 à 18 29 57" src="https://user-images.githubusercontent.com/68481856/146808297-bbca81a8-840a-4029-ab96-043f562f6e2a.png">

"h" is missing in "orthographic".

I'm sorry if this wasn't the right place for it. I'm still not used to Github.

**Comment by britzl** [comment]
Thanks!
