### ISSUE TITLE
lerp works difference in behavior in 2.3.1

### ISSUE THREAD

**Issue by TinyDobbins** [britzl/defold-orthographic#5]
before I set up the lerp by:
`msg.post("cameraGame", "follow", { target = followObject, lerp = 0.15 })`

now it looks like very lower.

**Comment by britzl** [comment]
Released a new version which fixes this. Old lerp values are now converted under the hood to work the same way as before.

https://github.com/britzl/defold-orthographic/releases/tag/2.3.2
