### ISSUE TITLE
camera.follow not working due to NAN value in camera_world_pos vector

### ISSUE THREAD

**Issue by Caue-Aron** [britzl/defold-orthographic#51]
In my game, I want the camera to follow this specific GO, but the camera instead rises this error:
`ERROR:SCRIPT: orthographic/camera.lua:419: argument #1 contains one or more values which are not numbers: vmath.vector3(nan, nan, 0)
stack traceback:
  [C]:-1: in function __add
  orthographic/camera.lua:419: in function update
  orthographic/camera.script:73: in function <orthographic/camera.script:71>`

I debugged and found out that this variable called `camera_world_pos` is recieving x and y values NAN. Giving an empty options table to the function won't rise any error, but the camera will not follow the target.

**Comment by Caue-Aron** [comment]
UPDATE: I FOUND WHERE THE BUG IS
The thing that turns `camera_world_pos` nan is this function, called at 367 in camera.lua:
```
local function lerp_with_dt(t, dt, v1, v2)
	if dt == 0 then return vmath.lerp(t, v1, v2) end
	local rate = UPDATE_FREQUENCY * math.log10(1 - t)
	return vmath.lerp(1 - math.pow(10, rate * dt), v1, v2)
end

```
rate is nan when camera.follow is called. I'm really bad at logarithm stuff.

**Comment by britzl** [comment]
Can you please share a zip with a project where this behaviour can be observed?

**Comment by Caue-Aron** [comment]
> Can you please share a zip with a project where this behaviour can be observed?

I removed the .internal, the game uses DefOS to do the mouse control. The script that raises the error is player.script, at line 191.

[Game.zip](https://github.com/britzl/defold-orthographic/files/8352904/Game.zip)

**Comment by britzl** [comment]
The project you shared is not complete. There is no game.project file and there are assets missing:

* title_screen.gui is referencing some template which doesn't exist
* There's a file Ror".png which seems to use a strange filename

I need a project which I can start and immediately observe the problem.

**Comment by Caue-Aron** [comment]
> The project you shared is not complete. There is no game.project file and there are assets missing:
> 
> * title_screen.gui is referencing some template which doesn't exist
> * There's a file Ror".png which seems to use a strange filename
> 
> I need a project which I can start and immediately observe the problem.

Oh much sorry, the Ror.png uses a ^, BR-PT symbol only, changed the files.
The problem happens when the tiny robot goes past the door at the right, from there theres a collision box which calls the problematic function from inside the player script (on_message function).
[game.zip](https://github.com/britzl/defold-orthographic/files/8355773/game.zip)

**Comment by britzl** [comment]
Found the issue. You set a lerp value larger than 1.0:

```
camera.follow(CAMERA_ID, hash("/camera_point_minigame"), {lerp = 2, offset = vmath.vector3(), horizontal = true, vertical = true, immediate = false})
```

The value should be within 0.0 and 1.0. I'll make a new release where a larger or smaller value is properly capped.
