### ISSUE TITLE
Add rotate towards mouse.

### ISSUE THREAD

**Issue by TheKing0x9** [britzl/defold-orthographic#6]

**Comment by subsoap** [comment]
What do you mean? Rotate the screen view?

**Comment by britzl** [comment]
I think this refers to: https://forum.defold.com/t/how-to-create-tds-look-at-mouse-solved/20702/12

I've added that the player character in the example project rotates towards the mouse coordinate. This uses camera.screen_to_world() and the world position of the player.

https://github.com/britzl/defold-orthographic/blob/master/example/player.script#L16-L20
