### ISSUE TITLE
FIXED_ZOOM projection works differently on Retina and non-Retina displays

### ISSUE THREAD

**Issue by Megus** [britzl/defold-orthographic#7]
I have "High DPI" setting enabled in project settings. Camera set to FIXED_ZOOM projection. When I run the game on non-Retina screen, everything is 2 times bigger, than on Retina screen.

**Comment by britzl** [comment]
This fix doesn't really work. It is not enough to check state of High DPI checkbox in game.project. You also need to know if the screen is a Retina screen or not.

**Comment by britzl** [comment]
I think you need to use [DefOS](https://github.com/subsoap/defos) or similar extension to query the scaling factor of the display.

defos.get_displays()[1].mode.scaling_factor

**Comment by britzl** [comment]
Added set_window_scaling_factor() to properly deal with this. Released 2.7.0.
